### Это файл нашей совместной работы, учимся NumPy

### Array

In [3]:
import numpy as np

In [4]:
# Cоздайте пустой массив из 0 (размерность 2х2)
np.zeros([2,2], int)

array([[0, 0],
       [0, 0]])

In [5]:
# Создайте массив с элементами [1,2,3], [4,5,6]
# На его основе создайте пустой массив
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty_like(X)

array([[6881377, 7536750, 4456540],
       [7602273, 4653153, 6881394]])

In [6]:
# Создайте одномерный массив из 50 элементов, где  все элементы лежат от 3 до 10
np.linspace(3,10,50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [10]:
# Выбрать диагонать матрицы
X = np.array([[ 0, 1, 2], [ 4, 5, 6], [ 8, 9, 10]])
np.diag(X)

array([ 0,  5, 10])

In [13]:
# Исследутие методы numpy.tri / numpy.triu   (методы, которые создают матрицу с заданой диагональю и 0 в других ячейках)
# Создайте при помощи этих методов матрицу, которая похожа на данную:
np.array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0, 12]])

#Внимание! Передать объект нельзя!

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [14]:
np.triu(np.arange(1,13).reshape(4,3),-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

### Basic Manipulation

In [20]:
# Конвертируйте данный массив в одномерный массив
x= np.array([[1,2,3],[4,5,6]])
y=np.column_stack(x)
np.concatenate(y)

array([1, 4, 2, 5, 3, 6])

In [25]:
# Преобразуйе два одномерных массива [1 2 3] и [4 5 6]
# в много мерный массив, где 2 колонки и 3 строки
x1 = np.column_stack(np.array([1,2,3]))
y1 = np.column_stack(np.array([4,5,6]))
x1 = np.column_stack(np.concatenate((x1,y1),axis=0))
x1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Вычислите скалярное произведение двух массивов (умножение матрцы)

<img src ="img/matrixdot.png" >

In [26]:
x = [1,2]
y = [[4, 1], [2, 2]]
np.dot(x,y)

array([8, 5])

In [29]:
# Определите в матрице все элементы True или есть False 
x = np.array([1,0,3])
np.all(x)

False

In [40]:
# Определите индексы элемента в матрице, который не False
x = np.array([1,0,0])
np.nonzero(x)

(array([0], dtype=int64),)

In [45]:
# дайте ответ, почему здесь такой ответ (все элементы True?)
x = np.array([1,0,'Text'])
np.nonzero(x)

(array([0, 1, 2], dtype=int64),)

In [52]:
x = np.array([1, 0, np.nan, np.inf])

# Какие результаты будут у следующех методов?
# np.isnan(x)
# np.isinf(x)
# np.isfinite(x)

In [56]:
# Получение реультатов из sum / prod
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = ["SUM",
        np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "PROD",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "CUMSUM",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "CUMPROD",
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "MIN",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "MAX",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "MEAN",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
           
for out in outs:
    if type(out) == str:
        pass
        print('\n')
        print("->", out, "<-" )
    else:
        pass
        print("->", out)



-> SUM <-
-> 36
-> [ 6  8 10 12]
-> [[10]
 [26]]


-> PROD <-
-> 40320
-> [ 5 12 21 32]
-> [[  24]
 [1680]]


-> CUMSUM <-
-> [ 1  3  6 10 15 21 28 36]
-> [[ 1  2  3  4]
 [ 6  8 10 12]]
-> [[ 1  3  6 10]
 [ 5 11 18 26]]


-> CUMPROD <-
-> [    1     2     6    24   120   720  5040 40320]
-> [[ 1  2  3  4]
 [ 5 12 21 32]]
-> [[   1    2    6   24]
 [   5   30  210 1680]]


-> MIN <-
-> 1
-> [1 2 3 4]
-> [[1]
 [5]]


-> MAX <-
-> 8
-> [5 6 7 8]
-> [[4]
 [8]]


-> MEAN <-
-> 4.5
-> [3. 4. 5. 6.]
-> [[2.5]
 [6.5]]


In [57]:
# Сделаем матричное разложение (почти рекомендашка )))
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
u,s,vh = np.linalg.svd(x)
print("u = {}\n s= {}\n vh = {}".format(u,s,vh))

u = [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
 s= [3.       2.236068 2.       0.      ]
 vh = [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]
 [-0.8944272  0.         0.         0.         0.4472136]]
